version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    weekday: 'monday'
    interval: weekly
    time: "04:00"
  target-branch: dependabot/merge
  reviewers:
  - cafca
  labels:
  - dependencies