version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  target-branch: dependabot/merge
  reviewers:
  - cafca
  labels:
  - dependencies
  ignore:
  - dependency-name: msw
    versions:
    - ">= 0.24.a, < 0.25"
  - dependency-name: "@testing-library/user-event"
    versions:
    - ">= 12.2.a, < 12.3"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@formatjs/intl-numberformat"
    versions:
    - 6.1.6
