[[redirects]]
    from = "/api/v1/*"
    to = "NF_API_URL:splat"
    status = 200
    force = true
    [redirects.headers]
        X-From = "Netlify"
        X-Forwarded-Host = "NF_API_HOST"
        X-Forwarded-Proto = "https"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
    for = "/api/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"