[[redirects]]
    from = "/api/v1/*"
    to = "https://api.fixmyberlin.de/api/:splat"
    status = 200
    force = true
    [redirects.headers]
        X-From = "Netlify"
        X-Forwarded-Host = "fixmyberlin.de"
        X-Forwarded-Proto = "https"

[[redirects]]
    from = "/api/next/*"
    to = "https://api-staging.fixmyberlin.de/api/:splat"
    status = 200
    force = true
    [redirects.headers]
        X-From = "Netlify"
        X-Forwarded-Host = "fixmyberlin-staging.netlify.app"
        X-Forwarded-Proto = "https"

[[redirects]]
    from = "/api/aachen/v1/*"
    to = "https://api.radbuegel-aachen.de/api/:splat"
    status = 200
    force = true
    [redirects.headers]
        X-From = "Netlify"
        X-Forwarded-Host = "radbuegel-aachen.de"
        X-Forwarded-Proto = "https"

[[redirects]]
    from = "/api/aachen/next/*"
    to = "https://api-staging.radbuegel-aachen.de/api/:splat"
    status = 200
    force = true
    [redirects.headers]
        X-From = "Netlify"
        X-Forwarded-Host = "fixmyaachen-staging.netlify.app"
        X-Forwarded-Proto = "https"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
    for = "/api/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
